### ISSUE TITLE
Validation artefacts

### ISSUE THREAD

**Issue by phax** [A-NZ-PEPPOL/A-NZ-PEPPOL-BIS-3.0#1]
Hi guys,
I heard that validation artefacts are close to ready. I would like to add them on peppol.helger.com as well, so any release would be appreciated :)
// Philip

**Comment by readethompsontrott** [comment]
Hi @phax,

They are now available. Please see the repository.

If you have any questions, please reach out to us at the email address provided in the README. If you notice any issues, feel free to raise them here on GitHub :) 

https://github.com/A-NZ-PEPPOL/A-NZ-PEPPOL-BIS-3.0/tree/master/Validation%20documents

Cheers,
R

**Comment by phax** [comment]
Thanks R for the swift response.
Do I get it right, that for "Invoice" I need to apply the Schematrons in this order:
1. AUNZ-UBL-validation.sch
2. AUNZ-PEPPOL-validation.sch

And for "Self-Billing" I'm apply those ones:
1. AUNZ-UBL-validation.sch
2. AUNZ-PEPPOL-SB-validation.sch

Are there any external Schematrons I need to reference? Any clarification helps. Thx :)

**Comment by readethompsontrott** [comment]
Hi @phax,

Apologies for the delay. I've had a chat to the team and we've decided that support documentation may be needed. We'll look into developing that. @HenryBuckMBIE will be able to confirm whether or not there are external Schematrons you need to reference.

In regards to the order, please see the image below.

![image](https://user-images.githubusercontent.com/22110846/67165746-5a539c00-f3e5-11e9-8d64-634d24a1de78.png)

Cheers,
R

**Comment by phax** [comment]
Thanks, that is all I needed - I will check back on you, once the validations are live
