### ISSUE TITLE
Please create release tags for 1.0.4 and 1.0.5

### ISSUE THREAD

**Issue by phax** [A-NZ-PEPPOL/A-NZ-PEPPOL-BIS-3.0#10]
Hi all,
Please add a "tag" and on top of that a "release" for the 2 versions, so that it is always clear which rules applied to that time:
See https://github.com/A-NZ-PEPPOL/A-NZ-PEPPOL-BIS-3.0/releases
Thanks, Philip

**Comment by AdrianGearing** [comment]
Release for v1.0.4 has been added
