### ISSUE TITLE
Some generic suggestions for improvement

### ISSUE THREAD

**Issue by phax** [A-NZ-PEPPOL/A-NZ-PEPPOL-BIS-3.0#2]
Hi guys,
a few things that came to my mind and will make life of us easier on a long term perspective:
* Can you please use the GitHub "release" feature and build dedicated release packages, so that old versions can be restored in case of question etc.
* Please assign each version a unique ID (as e.g. "1.0.1") so that people can get a common understanding of the problem, because people tend to not update their validation artefacts
* Please add the test files in the release package, because the test files will most likely also be changing over time
* I like, that the validation artefacts are licensed under Apache 2 license, but the test files are (at least partially - I haven't checked all) missing a license. Instead of marking every file (which would be desirable anyway) you could add a "LICENSE" file on top level of the respository, so the intent is also clear.
* Please elaborate when to use "AUNZ" and when to use "A-NZ" - I'm confused :-)

Thanks, Philip

**Comment by readethompsontrott** [comment]
Hi @phax,

I will be releasing 1.0.0 once the final guidance documents are available. Each release will have its own branch and the latest branch will be merge into master. We will be using semantic versioning.

In regards to the licensing, I will have a chat to the team on what we can do. I understand it's currently not very clear. Let me get back to you.

Thanks for your input.

Cheers,
Reade

**Comment by readethompsontrott** [comment]
I'll leave this ticket open until the licensing issue has been resolved.

**Comment by phax** [comment]
Okay thanks. This means what we currently have here is 0.9 or so?

**Comment by phax** [comment]
@readethompsontrott can you please enlighten me upon the current version number pls - thx. I just read somewhere that you called it "1.0.1" - thx

**Comment by readethompsontrott** [comment]
Hi @phax,

v1.0.1 was released last week. Prior to that, it was 1.0.0.

Cheers,
Reade
