### ISSUE TITLE
CreditNote examples would be nice

### ISSUE THREAD

**Issue by phax** [A-NZ-PEPPOL/A-NZ-PEPPOL-BIS-3.0#3]
Your test files are currenly pure UBL "Invoice" based.
You may consider some using UBL "CreditNote" to increase the test coverage for the validation rules, as they apply to both "Invoice" and "CreditNote".

**Comment by readethompsontrott** [comment]
Hi @phax,

CC: @HenryBuckMBIE 

There are very minimal differences between an Invoice and a Credit note. Nevertheless, I will make sure some examples are provided in the next release.

Cheers,
Reade

**Comment by readethompsontrott** [comment]
Hi @phax,

Release 1.0.2 has now been released. It contains `credit note` and `self billed credit note` examples.

[Click here to check them out!](https://github.com/A-NZ-PEPPOL/A-NZ-PEPPOL-BIS-3.0/tree/master/Message%20examples)

Cheers,
Reade

**Comment by phax** [comment]
Yes thanks, I saw that and already integrated it in peppol.helger.com 👍
