### ISSUE TITLE
Example does not pass validation

### ISSUE THREAD

**Issue by AlexanderKohl** [A-NZ-PEPPOL/A-NZ-PEPPOL-BIS-3.0#4]
When we run the message example "AU Invoice.xml" through the validator (https://aunz.validex.net/en/submit), it throws up 9 errors. Should we interpret this as a problem with the validator or the example file?

Also, it would be useful to add the xsd files to this repository. Is that possible?

Thank you
Alexander

**Comment by phax** [comment]
Hi Alexander,
you may try using it from https://peppol.helger.com/public/locale-en_US/menuitem-validation-bis2 - just select A-NZ... what you need.
The respective validation artefacts are:
* UBL 2.1 Invoice from http://docs.oasis-open.org/ubl/os-UBL-2.1/
* The Schematrons are in this repository at https://github.com/A-NZ-PEPPOL/A-NZ-PEPPOL-BIS-3.0/tree/master/Validation%20documents
hth

**Comment by readethompsontrott** [comment]
Hi @AlexanderKohl,

Can you please confirm you are still having issues?

Regards,
Reade
