### ISSUE TITLE
Example files not matching v1.0.4 rules

### ISSUE THREAD

**Issue by phax** [A-NZ-PEPPOL/A-NZ-PEPPOL-BIS-3.0#9]
The following rule is broken:
[BR-CO-19]-If Invoicing period (BG-14) is used, the Invoicing period start date (BT-73) or the Invoicing period end date (BT-74) shall be filled, or both.
Test: `((exists(cbc:StartDate) or exists(cbc:EndDate)) and not(exists(cbc:DescriptionCode))) or (exists(cbc:DescriptionCode) and (not(exists(cbc:StartDate)) and not(exists(cbc:EndDate))))`

This files are affected:
* `NZ Allowance On Invoice Line.xml`
* `NZ Credit note.xml`
* `NZ Invoice Level Allowance.xml`
* `NZ Invoice Level Charge.xml`
* `NZ No Allowances.xml`
* `NZ Prepaid Amount.xml`
* `NZ Self Billed Credit note.xml`
* `NZ Self Billing.xml`

**Comment by phax** [comment]
It works to just remove/comment the `<cbc:DescriptionCode>432</cbc:DescriptionCode>` part of the documents to make it work

**Comment by dmaus2018** [comment]
Seems to affect AU Invoice.xml as well

**Comment by phax** [comment]
I disagree to you @dmaus2018:
```xml
    <cac:InvoicePeriod>
       <cbc:StartDate>2019-06-01</cbc:StartDate>
       <cbc:EndDate>2019-07-30</cbc:EndDate>
    </cac:InvoicePeriod>
```
is according to the rules.

**Comment by dmaus2018** [comment]
Hi @phax 
If we add that description tag, it throws BR-CO-19; 
Does that mean description tag is not allowed ?  BR-CO-19 rule statement doesn't say anything about Description.
I noticed invoices coming to our access point have that description tag as well as startdate and enddate 
Ta

**Comment by phax** [comment]
The check means that either `StartDate` and/or `EndDate` OR `DescriptionCode` might be present but NOT both.
So if you use `DescriptionCode` make sure to remove `StartDate` and `EndDate`.

**Comment by jessie421998** [comment]
Thank you Philp and Deepesh!
I double checked that the sample file 'AU Invoice.xml' has passed validation (v1.0.4). 

The NZ team is working to update the rest of the sample files.  
Let us know if other questions or issues.
